apiVersion: policy.linkerd.io/v1beta2
kind: Server
metadata:
  name: backend
  namespace: todo
spec:
  podSelector:
    matchLabels:
      app: backend
  port: 5000
  proxyProtocol: opaque

---
# backend-server-authorization.yaml
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: backend-authz
  namespace: todo
spec:
  server:
    name: backend
  client:
    meshTLS:
      identities:
        - "frontend.todo.serviceaccount.identity.linkerd.cluster.local"
